### ISSUE TITLE
'DateField' always opens the Calendar downwards?

### ISSUE THREAD

**Issue by af7** [zippyui/react-date-picker#101]
I am not sure if there is an automatic setting (or even a manual setting) to allow the Calendar to open *above* the 'DateField' and not below. Our DateFields are at the bottom of the page...!

Is there such a setting?

If not, may I request for such?

Thanks!

**Comment by radubrehar** [comment]
`<DateField pickerPosition="top" />`
or
```jsx
<DateField>
   <Calendar position="top" />
</DateField
```

**Comment by af7** [comment]
Thank you!
I could not find this anywhere on your docs, I am pretty sure that I am also missing many other good features. Is there any plan to show all the available props soon? 

Thanks again, great project!
