### ISSUE TITLE
minDate exists, but it seems that I can choose a month before this `minDate`

### ISSUE THREAD

**Issue by af7** [zippyui/react-date-picker#104]
My `minDate` is April 27, 2016:

![image](https://cloud.githubusercontent.com/assets/7850073/16365114/fed30182-3bfe-11e6-81aa-e6d0017057af.png)

However, I can still choose a month below my minDate when clicking here:

![image](https://cloud.githubusercontent.com/assets/7850073/16365118/2ff563c2-3bff-11e6-8090-882d379981fb.png)

The result is that you are forcing (correctly) the calendar to the `minDate`, **but** you still say 'Feb' on the month title:

![image](https://cloud.githubusercontent.com/assets/7850073/16365124/6869a024-3bff-11e6-8dd1-15b50c3ac6b3.png)

Which is confusing, because I think that I can choose Feb 27, 2016 (which would be wrong). When clicking OK, the DateField says 'April 27, 2016' which is correct.

All I am saying is that the Month should never say 'Feb' and most likely we should not even be able to choose it, when a `minDate` exists.

Thanks!

**Comment by radubrehar** [comment]
Can you make sure you're using the latest version? Thanks.

**Comment by af7** [comment]
Thanks, I am using 5.3.12, isn't this the latest one?

**Comment by ersefuril** [comment]
This problem seems to be solved, I'm using the latest version (``react-date-picker@5.3.23 ``).

**Comment by dev-zippyui** [comment]
Thanks for the feedback!
