### ISSUE TITLE
Calendar closes when clicking on the Clock area

### ISSUE THREAD

**Issue by af7** [zippyui/react-date-picker#108]
When I click anywhere within the clock area, the Calendar closes unexpectedly (which is not what we want):

![image](https://cloud.githubusercontent.com/assets/7850073/16469620/bc57730c-3e5a-11e6-8325-bab37a790bb9.png)

Is this is bug? Can this not be happening? Thanks!

**Comment by radubrehar** [comment]
Fixed in `5.3.13` - just published on npm.

Thanks for reporting
