### ISSUE TITLE
Weekend highlight broken in latest (5.3.15)

### ISSUE THREAD

**Issue by tume** [zippyui/react-date-picker#116]
It seems that the latest version only highlights saturday with the finnish locale. It works fine with 5.3.14 version. Seems to be related these lines of code: https://github.com/zippyui/react-date-picker/blob/670fd033b8326716df781f510ec196c4b0e68ac1/src/MonthView/index.js#L375-L388

If understood correctly moment will return 0 for sunday and not 7 which this will expect if weekendStartDay is 6.

**Comment by radubrehar** [comment]
Thanks for reporting - was a regression introduced with #110 . I just reverted to the previous implementation, published `5.3.16` on npm and will reopen #110
