### ISSUE TITLE
IE10 is not supported?  'this' is undefined in renderDay(renderProps) function of MonthView

### ISSUE THREAD

**Issue by shuyon** [zippyui/react-date-picker#121]
this works on IE11 prefect, but not on IE10  and less.  got error like "SCRIPT5007 : Unable yo get property 'p' of undefined or null reference". this happens in MonthView  when run

 renderDay(renderProps) {
    const props = this.p
...
}

'this' in the function context is undefined.  I am trying to use plugins ["transform-es2015-classes", { "loose": true }],  "transform-proto-to-assign" in my babel-loader, but still having the same error. 

so do we support IE10 or not, or this is not a real issue just because I miss some settings for it?

**Comment by radubrehar** [comment]
We have to add this to our own `.babelrc` and republish the module.

**Comment by shuyon** [comment]
another option is install and import 'ima-babel6-polyfill', not elegant as above but works as well. thanks for the reply.
