### ISSUE TITLE
Calendar : Change time doesn't fire onChange prop

### ISSUE THREAD

**Issue by DonovanCharpin** [zippyui/react-date-picker#122]
Hi, 

I tried the Calendar component with the onChange prop. When I modify the date, the onChange method is called but it's not fired when I modify the time. If a value of my calendar is modified (date or time), I expect that my parent component knows.

Maybe I forgot something?

```
import { TransitionView, Calendar } from 'react-date-picker'
export default () => {
  return <TransitionView>
    <Calendar
      dateFormat="DD/MM/YYYY HH:mm:ss"
      defaultDate="20/04/2016 16:23:56"
      onChange={(dateString, { dateMoment, timestamp}) => {console.log(dateMoment)}}
    />
  </TransitionView>
}
```

**Comment by radubrehar** [comment]
`5.3.22` just published on npm fixes this! Thanks for reporting!

**Comment by DonovanCharpin** [comment]
Great! Just updated and it's fixed!

**Comment by dev-zippyui** [comment]
We just released a new version, with a fix for when dateFormat does not contain time information. Please make sure you update to the latest version!
