### ISSUE TITLE
Suggestion: add 'placeholder' prop

### ISSUE THREAD

**Issue by ersefuril** [zippyui/react-date-picker#123]
We cannot change input's placeholder in the latest version, this could be a small but nice improvement :)

**Comment by dev-zippyui** [comment]
See v `5.3.25` on npm. Thanks!

**Comment by dev-zippyui** [comment]
This could have been achieved even before `5.3.25`, with the following snippet

```jsx
<DateField
      dateFormat="YYYY-MM-DD"
      onChange={(dateFormat, {dateMoment}) => {
        console.log(dateFormat, '!!!');
      }}
>
  <input style={{color: 'red'}} placeholder="a placeholder here" />
</DateField>
```

**Comment by dev-zippyui** [comment]
Basically you have to nest an `input` inside the `DateField` in order to override the default input rendering & props.

**Comment by ersefuril** [comment]
I've just find out this few minutes ago xD 
Big thanks !
