### ISSUE TITLE
Suggestion: Exclude prop to grey out dates  

### ISSUE THREAD

**Issue by IntelvsAMD** [zippyui/react-date-picker#125]
[react-datepicker](https://github.com/Hacker0x01/react-datepicker/) allows an array of moment dates to be passed in the `excluded={}` prop. Every date on the date picker which is in the excluded prop will not be able to be selected.

Is this possible for `react-date-picker`?

**Comment by dev-zippyui** [comment]
Yep, use the `isDisabledDay(renderDayProps, props)` function prop and return true/false, based on whether the day is disabled or not. `renderDayProp` has a `dateMoment` and a `timestamp` property - that point to each day being rendered.

**Comment by dev-zippyui** [comment]
So basically this is much more flexible than a simple array of excluded days.

**Comment by im-fortech** [comment]
when I return true/false I get this error: 

> Warning: Unknown props `showClock`, `updateOnWheel`, `onTimeChange` on <div> tag. Remove these props from the element.

And the date does not get disabled ...
