### ISSUE TITLE
Pass date object to highlight dates in month view

### ISSUE THREAD

**Issue by nathan-bird** [zippyui/react-date-picker#132]
Is it possible to pass in an object with a bunch of dates and show those dates on the calendar?
I've had limited success with a single date passed through the date prop but cannot display multiple dates. 
Hopefully the image will illustrate what I'm looking for.
Many Thanks
![screen shot 2016-07-21 at 15 40 41](https://cloud.githubusercontent.com/assets/14997231/17024806/93329c08-4f59-11e6-8531-524f8200ab5e.png)

**Comment by dev-zippyui** [comment]
You should use the `onRenderDay` or the `renderDay` prop.

**Comment by nathan-bird** [comment]
Got it working! Thanks
