### ISSUE TITLE
Filtering specific dates (ie, making day item inactive in Calendar)?

### ISSUE THREAD

**Issue by Inlesco** [zippyui/react-date-picker#134]
I've used react-datepicker before and there was a prop 'filterDate' to which you can pass function that evaluates whether current dateObject should return true (active) or false (inactive).

Is there anything similar for the Calendar? I couldn't find a filterDate func. 

P.S. I've got a large array of dates and I'd like to filter them out efficiently.

**Comment by dev-zippyui** [comment]
See  #125

**Comment by Inlesco** [comment]
Thanks a lot! Problem solved :)

**Comment by dev-zippyui** [comment]
Great to hear that! As a result, we're closing the issue.
