### ISSUE TITLE
dateFormat not used everywhere

### ISSUE THREAD

**Issue by tume** [zippyui/react-date-picker#14]
It seems that if I specify some custom dateFormat it will set the correct date but fails to render it correctly e.g in MonthView.

I was quickly browsing through the code and it seems that some places moment is used like this:
<code>
            this.props.moment = moment(this.props.date).startOf('day')
</code>

So it is relying that moment(or Date) can parse that without explicitly passing the format. 
Related to this: https://github.com/moment/moment/issues/1407

**Comment by zippyui-react** [comment]
We've updated the code to make sure we parse dates with the specified `dateFormat`. For example, in the MonthView, we use `this.toMoment`, defined at line https://github.com/zippyui/react-date-picker/blob/master/src/MonthView.jsx#L86

If you want to render days/months/years in a different format, you can use `dayFormat` (eg: `dayFormat='DD')`, `monthFormat` and `yearFormat`.

Thanks for using the picker. Let us know if you have any other issues with the component.
