### ISSUE TITLE
how to config like the example, the props is so little, i can't config 

### ISSUE THREAD

**Issue by evilemon** [zippyui/react-date-picker#144]
![image](https://cloud.githubusercontent.com/assets/13042865/17433151/93bc418c-5b35-11e6-9b31-cc72a47d43cb.png)
how to config

**Comment by dev-zippyui** [comment]
Could you please be a bit more explicit? Thanks!

**Comment by evilemon** [comment]
hello, i mean that when i use DateField component, how can i set props to make it look like above

**Comment by evilemon** [comment]
for example how can i use DateField with Collapse_on_date_click like that, how to config

**Comment by dev-zippyui** [comment]
We'll come up with a tool to show code snippet you have to use in order to get the exact same configuration that you're building on our website.

**Comment by dev-zippyui** [comment]
`<DateField collapseOnDateClick={true} forceValidDate footer={false} />`

**Comment by evilemon** [comment]
yeah, i got it. And  updateOnDateClick={true} is needed, thank you
