### ISSUE TITLE
Customisation of  MultiMounthView: display an array of dates in defaultRange

### ISSUE THREAD

**Issue by erisnuts** [zippyui/react-date-picker#145]
Hello!
I need to display in MultiMounthView an array of dates like ['2016-08-01', '2016-08-03', '2016-08-10']. Can you please give me some advise?

**Comment by dev-zippyui** [comment]
You can use `renderDay` to basically control the rendering of any day in the view.

**Comment by erisnuts** [comment]
It dosen't work, falls with TypeError: renderFunction is not a function at MonthView.renderDay

**Comment by dev-zippyui** [comment]
Make sure `renderDay` you pass is a function.

**Comment by erisnuts** [comment]
Can you please give me example, I can't find any in Docs or code?...

**Comment by dev-zippyui** [comment]
See #5

**Comment by erisnuts** [comment]
thank you!
