### ISSUE TITLE
Document or support I18n

### ISSUE THREAD

**Issue by slorber** [zippyui/react-date-picker#15]
It seems hard to customize your lib for other languages like French, where the first day of week is Monday and translated as "Lun" instead of "Mon.

Can we do this easily inside your lib? Do we have to implement our own type of view?

**Comment by radubrehar** [comment]
Please use the latest 1.4.3 and see https://github.com/radubrehar/react-date-picker/tree/master#custom-locale

It should be as simple as doing  `require('moment/locale/fr')` before requireing the date-picker.

**Comment by slorber** [comment]
@radubrehar thanks but actually I can't select the locale in a "require" because I need the locale to be choosen dynamically from props

**Comment by radubrehar** [comment]
I understand. Expect a new release 2.0.0 somewhere next week in which I will try to adress this as well. The locale should probably be passed as prop of the date picker. What do you think?

**Comment by slorber** [comment]
yes that would be fine

will it change the order of the days of week in the month view according to the locale?

**Comment by radubrehar** [comment]
Not by default. I will introduce another prop weekStartDay, to dictate which day will be the first in the week. If this property is undefined (which will be the default), the locale will determine the week start day.

**Comment by slorber** [comment]
cool ping me when ready :) thx

**Comment by radubrehar** [comment]
Hi Sébastien.

as discussed, we have released version 2 of the datepicker.

You now have a `locale` prop, which, if your locales are loaded, works as expected. Also added a bunch of other features. Please read the [changelog](https://github.com/zippyui/react-date-picker/blob/master/CHANGELOG.md)

NOTE: onChange, onSelect, onNav args have changed order, so first arg is the dateString, second arg is the moment instance.

The date picker now has a new home: https://github.com/zippyui - we are releasing a bunch of other UI carefully crafted widgets on top of React.

**Comment by slorber** [comment]
thanks will check that when I get back from holidays

**Comment by slorber** [comment]
@radubrehar it seems to work fine in our app thanks

**Comment by zippyui-react** [comment]
Great to hear that.
Radu
