### ISSUE TITLE
highlightRangeOnMouseMove does not work

### ISSUE THREAD

**Issue by cubbuk** [zippyui/react-date-picker#150]
I am trying to highlight the range on a `MultiMonthView` component, I found out from the source code that the required prop to enable that is `highlightRangeOnMouseMove` but it doesn't work as expected. Can anyone point me onto direction how to use it?

Here are what I have tried so far?

```
      <MultiMonthView minDate={now}
                                   range={[startDate, endDate]}
                                   defaultRange={[Date.now(), Date.now()]}
                                   highlightRangeOnMouseMove
                                   onRangeChange={this.rangeChanged.bind(this)}/>
```

I tried to use `rangeStart` but to no avail

```
    <MultiMonthView   minDate={now}
                                   range={[startDate, endDate]}
                                   defaultRange={[Date.now(), Date.now()]}
                                   highlightRangeOnMouseMove
                                   rangeStart={moment(startDate)}
                                   onRangeChange={this.rangeChanged.bind(this)}/>
```

**Comment by dev-zippyui** [comment]
You are using both `range` and `defaultRange` - so both controlled & uncontrolled versions of range prop. You should only use one of them - try `defaultRange`.

**Comment by cubbuk** [comment]
@dev-zippyui thanks using `defaultRange` instead of `range` worked.
