### ISSUE TITLE
How to correctly toggle between Single/Range date picker?

### ISSUE THREAD

**Issue by erisnuts** [zippyui/react-date-picker#151]
I understand, that to get range-date-picker I need to set prop defaultRange, and to get single-date-picker - not.
But I can't toggle this prop during run-time - widget does not updates. 
forseUpdate don't work either.

**Comment by dev-zippyui** [comment]
Yep, we thought this is not a very common scenario, so not supporting this dirrectly. If you want to do this, just pass a `key` prop when single date picker, and another value for the `key` prop when switching to range date picker. This will force the component to unmount and then mount again with a different configuration.

**Comment by dev-zippyui** [comment]
Example:

`<DatePicker key="single" ... />` => `<DatePicker key="multi" ... />`

**Comment by erisnuts** [comment]
Thank you! It works!

Now there is a problem with first selected range (after toggle single -> multi). 
Function onRangeChange returns ["Invalid date", "2016-09-16"].

**Comment by dev-zippyui** [comment]
Can you describe the scenario more accurately and provide some minimal code snippet to illustrate this.

**Comment by erisnuts** [comment]
1) toggle <DatePicker key="single" ... /> => <DatePicker key="multi" ... /> 
2) trying to select startDate of date-range - clicking on alendar one time
3) function onRangeChange returns value ["Invalid date", "2016-09-15"]
Further date selection works properly.

**Comment by dev-zippyui** [comment]
Okay, will try to repro. Thanks!

**Comment by erisnuts** [comment]
Sorry, that was my mistake! Widget works perfectly fine!)

**Comment by wouterwisselink** [comment]
Hi @dev-zippyui,

It looks like this doesn't work in the current version anymore, is that correct?

**Comment by erisnuts** [comment]
Check out Range selection checkbox on http://zippyui.com/docs/react-date-picker/examples/1

**Comment by wouterwisselink** [comment]
Thanks @erisnuts, but that's not working for me.. I've tried to explain my problem over here: https://github.com/zippyui/react-date-picker/issues/190
