### ISSUE TITLE
DateFileld dosen't lose focus after date selection

### ISSUE THREAD

**Issue by erisnuts** [zippyui/react-date-picker#154]
`collapseOnDateClick: true,
expandOnFocus: true`

click on date in calendar collapses it, but focus staying on DateField, as a result user can't expand it on focus ones more.
[example](http://zippyui.com/docs/react-date-picker/examples/0) acts the same way.

How can remove focus from DateField after collapseOnDateClick ?

**Comment by erisnuts** [comment]
onChange: (nextValue) => {
        document.activeElement.blur();
      },

**Comment by dimafeldman** [comment]
Thank you so much! was totally worth it searching the issues section :)
