### ISSUE TITLE
Theming the component

### ISSUE THREAD

**Issue by jgknott** [zippyui/react-date-picker#156]
I'm probably making a newbie mistake.. but when I try to import my theme I get this:
`react-date-field--theme-[object Object]`

![image](https://cloud.githubusercontent.com/assets/10761004/17723986/974a6396-63fb-11e6-8fac-42e8e3741b5f.png)

Here's my code.. Any ideas what I'm doing wrong?

```
import theme from './datepick.scss'
import {DateField} from 'react-date-picker'


class Timer extends Component {
	constructor(props) {
		super(props)
	}

	render() {
		return (
			<div className= "hbox ">

				<div className="hbox align-center justify-center flex ">
					<DateField theme={theme}/>
    		</div>

			</div>
		)
	}
}
```

**Comment by dev-zippyui** [comment]
The `theme` prop needs to be a `string`
