### ISSUE TITLE
Option to disable setting date from the past.

### ISSUE THREAD

**Issue by padsbanger** [zippyui/react-date-picker#164]
Hello, 

I am using this component in my appointment booking app, and I want to disable selecting date from the past is there an option to achieve this ?

**Comment by dev-zippyui** [comment]
Specify `minDate`

**Comment by padsbanger** [comment]
Thanks 👍

**Comment by danielfms** [comment]
how can I disable selecting past time with minDate?

**Comment by madhur** [comment]
Where is the documentation for `minDate` ?
