### ISSUE TITLE
the component always shows "invalid date".

### ISSUE THREAD

**Issue by codepandy** [zippyui/react-date-picker#175]
when the page was initialized,the DateField showed "invalid date",whether set defaultvalue or not.

**Comment by codepandy** [comment]
who could solve this problem?

**Comment by ferrwanz** [comment]
Can you show your codes ?

If you pass a wrong value of date, of course it will show "invalid date" text
Make sure you didn't pass a wrong date. 
If your date value is `1932-11-21T00:00:00+0730 `, in value attribute you can make it like this:
`value={ new Date(1932-11-21T00:00:00+0730) }`

**Comment by codepandy** [comment]
@ferrwanz I didn't set value.the below is my code.
`<DateField forceValidDate={true}  defaultValue={"2016-05-30 09:23 AM"} updateOnDateClick={true} dateFormat="YYYY-MM-DD hh:mm a"/>
<DateField forceValidDate dateFormat="YYYY-MM-DD hh:mm a"/>`
I remember that it could work properly on the first day.

**Comment by wzup** [comment]
@ferrwanz 

>  value need be converted to date type.

Who said that? Look at the examples from docs, it is a plain vanilla `string` not a  `date type`:

![date-picker - google chrome 2017-01-17 08 56 48](https://cloud.githubusercontent.com/assets/3880497/22004003/f60c7026-dc92-11e6-9ce7-8afc6f523c3f.png)

Seems like author doesn't bother to provide any meaningful documentation
