### ISSUE TITLE
how to hide the ok button?

### ISSUE THREAD

**Issue by codepandy** [zippyui/react-date-picker#178]
There aren't api on your website,why?just a little example. It is difficult to know what the component properties' name are.
I hope that you can list the component's properties.

**Comment by themre** [comment]
`okButton={false}`. Or if you hide footer, then you're also without it.Actually here is probably a bug, since the code doesn't update correctly (http://zippyui.com/docs/react-date-picker/examples).

**Comment by codepandy** [comment]
okButton={false} is  invalid.

**Comment by themre** [comment]
which version are you using? mine is 5.3.28. And this is my code:
```
 <MonthView
                            onChange={this.onDayPicked}
                            okButton={false}
                            theme={null}
                            onRenderDay={this.onDay}
                            highlightWeekends={true}
                            highlightToday={true}
                            weekNumbers={false}
                            highlightRangeOnMouseMove={false}
                            weekStartDay={1}
                            footer={true} />
```

**Comment by codepandy** [comment]
My version also is 5.3.28, and this is my code:

`
 <DateField forceValidDate
                    dateFormat="YYYY-MM-DD hh:mm a" okButton={false}
                    onChange={_self.endDateHandle.bind(_self)}
                    />
`

**Comment by themre** [comment]
no, you need to put that prop in MonthView or Calendar. I use MonthView.
```
<DateField>
     <MonthView okButton={false} />
</DateField>
```

**Comment by codepandy** [comment]
cool,but how to hide the panel when I select a date?

**Comment by themre** [comment]
updateOnDateClick={true}. use this APi builder, because a lot of things 
works (except OK button) :) 
http://zippyui.com/docs/react-date-picker/examples

**Comment by codepandy** [comment]
I set the property,but the panel don't automatic hide.

**Comment by themre** [comment]
|updateOnDateClick={true} collapseOnDateClick={true}|

**Comment by codepandy** [comment]
You are awesome,I'm a big fan of you.
but it still have a big bug,do you know how to solve it?
the bug url:
https://github.com/zippyui/react-date-picker/issues/180

**Comment by themre** [comment]
replied in that ticket. btw, I'm just using this component, not the 
author ;) perhaps you can close this ticket and the previous if it was 
solved.

**Comment by codepandy** [comment]
ok,thank you very much,I will close this ticket.
