### ISSUE TITLE
Blue circle on date does not disappear after value changed

### ISSUE THREAD

**Issue by justyun** [zippyui/react-date-picker#193]
When the user clicked on a date, the date number becomes blue with a blue circle. When the date value is changed by the props, the blue background is changed to the new date, but the blue circle remains at the old date.

**Comment by dev-zippyui** [comment]
The blue circle represents the `activeDate`, while `value` represents the selected date. When you click a date, both `activeDate` & `value` are set to the clicked date. However, you can use keyboard navigation to navigate to another active date, and use enter to confirm and choose the selected `value`. This is the intended behaviour.
