### ISSUE TITLE
picking time of day

### ISSUE THREAD

**Issue by yonatanmn** [zippyui/react-date-picker#20]
Hi,
This is a really nice date picker, and I'm using it in my work.  
I'd like to contribute by adding the ability to choose time of day (only as an option)
Do any one have any UI ideas for how to implement that?
I thought about adding another `ClockView` or adding a line beneath `MonthView`. 

Please tell me what you think about that,
Yonatan

**Comment by zippyui-react** [comment]
Hi Yonatan,

we are very glad to hear the date picker is useful to you. Please have a look at our time picker at http://zippyui.github.io/react-time-picker/

Do you think you can use these in combination? We'd like to hear your thoughts.

**Comment by yonatanmn** [comment]
I've seen that, but I think integrating both will be overkill, especially since the functionality is quite different, and I'm new to those repositories

**Comment by zippyui-react** [comment]
We can build an example, so you can easily follow. So you'd like to show the picker under the calendar? Coming back soon with an example, and we can discuss it even further to customize it.

**Comment by yonatanmn** [comment]
Yea, that will be cool !

**Comment by yonatanmn** [comment]
Take a look at this - 
http://dev.quri.com/react-bootstrap-datetimepicker/

**Comment by zippyui-react** [comment]
That looks good, we're coming up with a solution. May relate to #21

**Comment by yonatanmn** [comment]
Hi, any news?
Please let me know since I need it for a project I'm currently working on, and I might start doing this myself (probably detached from this project)

**Comment by zippyui-react** [comment]
As promised, we've built an example to on top of the date picker and the time picker. Check it out at https://gist.github.com/zippyui-react/fac89a1ee7da943c5b38

We've updated the datepicker to v 2.0.18, please make sure you use that with the example above, since we've exposed some new public props. You'll also need to install `react-time-picker`

**Comment by zippyui-react** [comment]
Let us know how it goes :)

**Comment by yonatanmn** [comment]
Hi, 
First - thanks a lot for your work, 
Second - It's not really working for me: 
I have `DatePicker` working in my project with a lot of surrounding logic which I rather not touch. I control the date with `timestamp` unix time.
To add Time,  I just changed  `DatePicker`  to the component you created (`Picker`). The design of `TimePicker` doesn't fit (small css fixed), but the real problem was that when I changed time, `TimePicker` started doing infinite loop - the numbers in display  went crazy, but the retrieved time wasn't changing. Also, propbably because of the infinite loop, when unmounting higher Component - I sometime  got this error : `Uncaught Error: Invariant Violation: replaceState(...): Can only update a mounted or mounting component.1`.

**Comment by yonatanmn** [comment]
After some more checks - I think it's solely a problem of `TimePicker` 
See [this](https://github.com/zippyui/react-time-picker/issues/5) for details

**Comment by zippyui-react** [comment]
Make sure you provide an `onChange` callback to the picker, and update the picker value, and then refresh the component. If you have controlled behaviour (ie, you use `value` instead of `defaultValue`), the value in the picker will not change if you don't change it.
