### ISSUE TITLE
Integration with input element

### ISSUE THREAD

**Issue by hoangmphung** [zippyui/react-date-picker#21]
Hi,

Very nice date picker. I need to implement a form with a date input, which pops up a date picker if the user clicks on it (or clicks an icon next to it). I can manually do the integration for the time being but I think it is a pretty common requirement to warrant built-in support.

**Comment by zippyui-react** [comment]
Yes, thanks for bringing this up. We have already implemented this, and will be publishing it this week.

Appreciate you're using the date picker and hope you'll find the date field useful as well. I'll comment on this issue as soon as we publish.

**Comment by cubbuk** [comment]
Hi,
Is there any progress on this issue, is there any support for input integration?
Thanks

**Comment by AlbertAlquisola** [comment]
Hi, agree with cubbuk.  I'm about to use this datepicker (its great) but input integration is a requirement.  Any updates?

**Comment by radubrehar** [comment]
Sorry for the long delay. Hope we can launch an integration next week. This time for real :)

Thanks for your patience.

**Comment by AlbertAlquisola** [comment]
thanks, please let us know when its updated

**Comment by radubrehar** [comment]
Yes, we're on it

**Comment by zawilliams** [comment]
Interested in using it with an input as well.

**Comment by AlbertAlquisola** [comment]
Any updates on this?

**Comment by nunogoncalves** [comment]
+1 for this. Also need it. :)

**Comment by mqklin** [comment]
+1, i cant use it, because i need input :(

**Comment by radubrehar** [comment]
We've just released https://github.com/zippyui/react-date-field, which might be rough around the edges, but should get the job done!

**Comment by radubrehar** [comment]
We're closing this as our react-date-field covers this pretty well.

**Comment by radubrehar** [comment]
Hey, so many requests here for this, but no feedback after this is released...

**Comment by mqklin** [comment]
@radubrehar, I've chosen another date-picker and now I haven't time to move from it to your solution.

**Comment by AlbertAlquisola** [comment]
Haven't tried to use it yet, will leave feedback once I integrate it
