### ISSUE TITLE
Existing test failing

### ISSUE THREAD

**Issue by koustuvsinha** [zippyui/react-date-picker#22]
So I cloned this repo and run the tests as per instructions, but the tests are failing like this : 

```
DatePicker
    1) renders selected date - also make sure no crash on null date
    2) render defaultDate and make sure click on date works


  0 passing (244ms)
  2 failing

  1) DatePicker renders selected date - also make sure no crash on null date:
     TypeError: undefined is not a function
      at module.exports (test/testdom.js:5:21)
      at Context.<anonymous> (test/DatePickerTest.js:25:29)

  2) DatePicker render defaultDate and make sure click on date works:
     ReferenceError: document is not defined
      at render (test/DatePickerTest.js:10:22)
      at Context.<anonymous> (test/DatePickerTest.js:61:22)



make: *** [test] Error 2
```

What should be the issue? I have installed iojs for the jsdom to work.
On further inspection, the error pops up in this line of [code](https://github.com/zippyui/react-date-picker/blob/master/test/testdom.js#L5)

**Comment by zippyui-react** [comment]
We just tried the tests, and indeed, thy are failing. The problem is with the jsdom version, we have specified "jsdom": "^4.1.0", so when you install the package, it installs a version close to 4.1.0 and that version has some issues.

We've updated the dev depencies, you should be fine now. Check out the master branch

PS: v 2.0.16 on npm

**Comment by koustuvsinha** [comment]
Yes the tests are passing now. Thanks!
I still dont get why are you using the Makefile where you could have provided the test command in the package.json itself

**Comment by zippyui-react** [comment]
Ok, we've moved them to package.json, and refer them from the Makefile as well.

So you can now run `npm test` as well.
Thanks
