### ISSUE TITLE
a warning after Updating to 2.0.18,

### ISSUE THREAD

**Issue by yonatanmn** [zippyui/react-date-picker#23]
Got this (after upgrading version from 1.4.2):
`Warning: DatePicker is calling a React component directly. Use a factory or JSX instead. See: http://fb.me/react-legacyfactory`

**Comment by zippyui-react** [comment]
What version of React are you using?

**Comment by yonatanmn** [comment]
react@0.12.2

**Comment by zippyui-react** [comment]
The component works on react 0.12.2, but we're suggesting using 0.13.x. As Facebook releases 0.14 soon, you should upgrade at your earliest convenience, so you don't risk being left behind on features.
