### ISSUE TITLE
Disable year and decade view

### ISSUE THREAD

**Issue by danielbuechele** [zippyui/react-date-picker#26]
Perhaps I just don't get how, but I would like to disable all views, but the month view. So clicking on the month shouldn't do anything.

**Comment by zippyui-react** [comment]
You can simply use the controlled behaviour for the `view` property (and not provide an onViewChange callback)

```jsx
<DatePicker view='month' defaultDate={Date.now()}/>
```

Let us know if it's ok for you

**Comment by danielbuechele** [comment]
that was easy! Cheers!
