### ISSUE TITLE
Add on* methods to propTypes

### ISSUE THREAD

**Issue by johncblandii** [zippyui/react-date-picker#27]
I had to read the code to find the event handlers for date selection. It would be great if the `onSelect` and `onNav` methods were in `propTypes`, along with any others.

**Comment by zippyui-react** [comment]
Thanks for pointing that out. We'll add them to propTypes as well. They are already in the README docs, so no need for someone to read the source to find that out. But it's a good idea to add them to propTypes too.

**Comment by johncblandii** [comment]
True on docs. I was in the code already so just went there to find the props, easier read than perusing docs.

**Comment by zippyui-react** [comment]
Glad to hear the source was easy to digest. Yep, the source remains the true source of truth :)

**Comment by radubrehar** [comment]
We've updated the date picker to add props on the propTypes. Released 2.1.9 on npm. Hope you'll find it useful.

**Comment by johncblandii** [comment]
Good deal.
