### ISSUE TITLE
add option to highlight one or more dates

### ISSUE THREAD

**Issue by luisrudge** [zippyui/react-date-picker#34]
Imagine a range picker scenario:

![image](https://cloud.githubusercontent.com/assets/941075/8065205/5ea4aac4-0eb6-11e5-9116-197ee81bb28a.png)

I'd like to highlight all the selected range, but there's no api to do that.

**Comment by luisrudge** [comment]
Sorry. Just saw this: https://github.com/zippyui/react-date-picker#custom-styling-of-day-cells

**Comment by radubrehar** [comment]
Great!

**Comment by themre** [comment]
I can't seem to find this option. Where is this located now?
