### ISSUE TITLE
Implementing data range with component ?

### ISSUE THREAD

**Issue by labithiotis** [zippyui/react-date-picker#39]
How easy would it be to implement a mechanic to select a date range between two dates.
Something like this? (Ideally on just one calendar)
 ![Example](https://camo.githubusercontent.com/1083660a91a3d95a2dd4e8e5e74dfc9703fcdadd/687474703a2f2f692e696d6775722e636f6d2f4c62414d6633442e706e67)

**Comment by cocodrino** [comment]
+1 I'd love that feature...

**Comment by radubrehar** [comment]
See #60 . Not multi-view yet, but works nice.

**Comment by radubrehar** [comment]
v `5.3.2` released on npm includes range selection & multi month views. See http://zippyui.com/docs/react-date-picker/examples/1 for an example

**Comment by tzookb** [comment]
Hi @labithiotis have you done your project already?

how did you handle the "onRangeChange" that fires twice?

**Comment by radubrehar** [comment]
@tzookb you should check for a valid range - since on first click, when you only have the initial moment selected it fires with [start], and then, when you select the end, it fires with [start,end]. It's by design, and you can filter your processing based on whether the range is complete or not

**Comment by tzookb** [comment]
thanks @radubrehar ,

but it fires twice only after the second click, and on both fires I have 2 valid dates.

On my first click I get an empty array,
second click I get an array with 2 dates, and get this event twice
