### ISSUE TITLE
Any time-picker usage for this plugin?

### ISSUE THREAD

**Issue by yhjor1212** [zippyui/react-date-picker#40]
Thanks!

**Comment by Andreyco** [comment]
https://github.com/zippyui/react-time-picker

**Comment by radubrehar** [comment]
See our new v `5.3.2` released today on npm and http://zippyui.com/docs/react-date-picker/examples/0

We have input & time formats integration in the new version. Hope it helps :)
And a nice looking css clock input as well :)
