### ISSUE TITLE
react 0.14.0-rc1

### ISSUE THREAD

**Issue by growlsworth** [zippyui/react-date-picker#48]
wanted to check to see if the package.json could be updated to support react 0.14

**Comment by radubrehar** [comment]
It should, since `package.json` specifies `"react": ">=0.12.0 || ^0.14.0-alpha"` as dep

**Comment by aft-luke** [comment]
Does `^0.14.0-alpha` also include the newly released `0.14.0`?

**Comment by radubrehar** [comment]
Will have a look at this on monday. Thanks

**Comment by radubrehar** [comment]
We've just released `3.1.7` on npm, with a `>=0.12` peerDependency on `react`

**Comment by radubrehar** [comment]
Let me know how it goes

**Comment by aripalo** [comment]
Haven't used extensively, but so far has worked well for me with `react@0.14.0` :+1: 

Great component, btw! Cheers!
