### ISSUE TITLE
Disallow user from navigating to another view after/before a given date

### ISSUE THREAD

**Issue by mr-wildcard** [zippyui/react-date-picker#51]
Hi,

[jsbin example](https://jsbin.com/bijahipapu/2/edit?html,css,js,output) : I don't want users to access August 2014 nor December 2014

Thanks ;)

(nice component btw)

**Comment by radubrehar** [comment]
Use the controlled `viewDate` and `onViewDateChange` props to control that. Let me know how it goes.

**Comment by mr-wildcard** [comment]
Hm, I don't really get it :D
All provided functions are some sort of "after" events, right ?
Internally, there is no system like "before" events, allowing us to simply stop event propagation and the date-picker from updating.. right ?

Correct me if I'm wrong, the only solution left to me would be to listen to `onViewDateChange`, then change the state of my parent component in wich I set/update a `viewDate` property wich I then send down to you date-picker component ? This `viewDate` property could be the same as the previous one if I don't want the user to navigate, or a new one to allow the navigation.

**Comment by radubrehar** [comment]
Yes, there's no before or after evens in React. Controlled props to the rescue! This is the React way of doing things. When the user clicks next/prev, this is signalled in `onViewDateChange`. It's up to you to change the controlled `viewDate` prop to make the navigation happen, or to navigate two months instead of one, or to cancel it altogether. This is a very powerful mechanism React offers. Exposing controlled props in a component (eg, the date picker) makes it very flexible and allows users of the component implement scenarios that the component creator may be unaware of.

**Comment by mr-wildcard** [comment]
I agree and I know for sure that React doesn't have jquery-plugin-ish events ;)

But I try to keep most of my components stateless, and not having a way to simply `.preventDefault` on a view change event (before you internally update the date picker), forces me to store the current `viewDate`'s value of my date picker inside of its parent component state.

As I see it, when I click on the arrow to change the view:
1. date picker is automatically updated no matter what
2. then you call my provided callback for `onViewDateChange`
3. from within my callback I decide wether or not the date picker should keep this view displayed
4. I decide that user should not be able to access this `viewDate`, so I force my component + yours to re-render with correct `viewDate` value:
```
// parent component
this.setState({
  viewDate: allowedViewDate
}):
```

... or am I really missing something ? :)

Btw, I tried what's listed above but `viewDate` doesn't seems to be updated. At this point I don't know if I screwed something or if I'm encoutering https://github.com/zippyui/react-date-picker/issues/25

Thank you for your help.

**Comment by radubrehar** [comment]
If you specify a `viewDate`, the date picker internally is not updated at all.
If instead you don't specify a `viewDate` (or if you specify a `defaultViewDate`), then yes, the picker updates itself.

So if you specify a `viewDate`, the prev/next buttons just call your `onViewDateChange` fn prop, where you should update `viewDate` (either in your app state, if you are using redux/flux, or in your parent component state). When you update the `viewDate`, the picker is rendered accordingly.

I think you need a better understanding of controlled props, so let me know if I can help.

**Comment by mr-wildcard** [comment]
Ok. Now I get it :) and I think this is what confused both me and @mmw in his https://github.com/zippyui/react-date-picker/issues/25 who also tried `viewDate` without controlling its value with `onViewDateChange`

I'll try this out, thx !

**Comment by radubrehar** [comment]
Glad to help. Yes, grasping controlled props is a bit difficult at the begining, but once you realise the power they offer, you never go back again.

Let me know how it goes.

**Comment by radubrehar** [comment]
I suppose everything is fine, so closing this.
