### ISSUE TITLE
Today, Go to selected buttons are broken.

### ISSUE THREAD

**Issue by mwkang** [zippyui/react-date-picker#52]
![11](https://cloud.githubusercontent.com/assets/10624086/10876758/fdab6196-8182-11e5-9cf8-3c9c2df4bd8d.png)
Today is 11/02.
I selected 11/12 and clicked the Today.
But It didn't work. What's the problem?

**Comment by radubrehar** [comment]
It only navigates to today. Just like "Go to selected" only navigates to the selected day, "Today" navigates to the current day.

**Comment by mwkang** [comment]
Ah~ I know I have a confusion.
Thanks!!

**Comment by timscott** [comment]
It seems ```onChange``` is not fired. Is there an event fired when Today is clicked?

**Comment by timscott** [comment]
I might be mistaken about ```onChange``` being fired. I was confused because Today does not select today but whatever date is ```date``` prop. It might be better is Today selection the actual today,

**Comment by radubrehar** [comment]
The today button only navigates to today, but does not do any selection. It only changes the viewDate, so you should have onViewDateChange fired

**Comment by timscott** [comment]
That does it. Thanks.

**Comment by timscott** [comment]
Except  ```onViewDateChange``` is also fired when moving between periods. I would like for clicking Today to mean "I choose today" just as if I clicked on that date. Otherwise I would like to hide the link.

**Comment by timscott** [comment]
If I set ```todayText``` to "This Month" it works out okay. That's what it does it seems, navigates to the current month.
