### ISSUE TITLE
minimum react version

### ISSUE THREAD

**Issue by fremn** [zippyui/react-date-picker#58]
package.json specifies  `React >=0.14.0`

but the readme talks about `react 0.12` given that the reacts 0.13 to 0.14 change was breaking with the react-dom split im guessing the package.json is the authority on this. 

not an issue for me as i'm on 0.14 but i figure it could help others to update this

**Comment by radubrehar** [comment]
While we actively push for 0.14, the code is/was actually retrofitted to support `0.12`, but it's a good idea to remove the 0.12 support from readme. Thanks for the notice!
