### ISSUE TITLE
Add `range` support

### ISSUE THREAD

**Issue by radubrehar** [zippyui/react-date-picker#60]
We need to support the controlled `range` prop and the `onRangeChange` prop callback

```jsx
const range = [start, end] 
//or range = []
//or range = [start]

<DatePicker range={range} onRangeChange={onRangeChange}/>
```

Also, we need support for `defaultRange` uncontrolled prop.

```jsx
const range = []
<DateRange defaultRange={range} />
```

**Comment by albertogasparin** [comment]
:+1:  This feature would be super handy!

**Comment by radubrehar** [comment]
It's already pushed on master. Expect it to be released on npm this week! Thanks for your patience!

**Comment by albertogasparin** [comment]
I've tested v4.0.7 and it is working fine :wink: 
Thanks for this great (and small) lib!

**Comment by radubrehar** [comment]
@tzookb github says you unassigned @LucaBecea. How is that possible, since you don't have access rights on the repo?

**Comment by tzookb** [comment]
:D. Mmm don't know what happens :/

Only added a comment.....
