### ISSUE TITLE
The npm dist points to the lib folder but the style files are not there...

### ISSUE THREAD

**Issue by shaimo** [zippyui/react-date-picker#61]
I guess there is no way to include the styles unless I move the files elsewhere or change the package.json file?

**Comment by radubrehar** [comment]
You should be able to find the styles in the root folder, so just `require('react-date-picker/index.css')`

**Comment by shaimo** [comment]
That doesn't work (getting Uncaught Error: Cannot find module "react-date-picker/index.css") because 'main' in the package.json file points to lib/index.js and not to the root folder. Either need to change main to point to the root, or make sure the style files are also available in the lib folder...

**Comment by radubrehar** [comment]
`main` in `package.json` points to the entry point, that you can directly require. Other than that, `main` does nothing special.

**Comment by shaimo** [comment]
Thanks. Learning a new thing every day...:-)

**Comment by radubrehar** [comment]
Sure, no problem! Hope you'll find the datepicker useful!
