### ISSUE TITLE
Update for React 15

### ISSUE THREAD

**Issue by slorber** [zippyui/react-date-picker#67]
Hi

Can you please support new release of React? 15.0.0-rc.1

**Comment by radubrehar** [comment]
Sure :) will solve this today

**Comment by radubrehar** [comment]
There you go :+1: `4.0.10` is on npm now with support for `15.0.0-rc1`.

Thanks @slorber for being so proactive :) I assume you're using `react-date-picker` quite a lot in your apps. Do you have any screenshots you can share with the community or any feedback on what we could improve? Thanks!

**Comment by slorber** [comment]
Hi and thanks,

We use it at Stample.co

I've not worked much on it but will probably try to migrate to React 15 asap so I open github issues everywhere I need ;)

Here's a screenshot of our next release (not prod ready yet)

![image](https://cloud.githubusercontent.com/assets/749374/13670784/29fe0998-e6cc-11e5-8ac9-4c5d22f4cef0.png)

**Comment by radubrehar** [comment]
Would you mind us adding your app into a "Who's using our components?" page?

**Comment by slorber** [comment]
no problem
