### ISSUE TITLE
month and year view

### ISSUE THREAD

**Issue by nickmayorga** [zippyui/react-date-picker#68]
hi! thanks for such a wonderful little component!

I have been using it to make a combo text input and date picker and had a question: would overriding the onChange callback for DatePicker affect the ability to select months and years from their respective views? Currently, I am able to drill up into those views, but when I make a selection, nothing is happening.

Thanks!

**Comment by radubrehar** [comment]
`onChange` is not called when the user selects a month or a year - is this what you want? Clicking a month or a year only changes the current view. Maybe you could use the `onViewChange` prop to hook into that, and use a controlled `view` prop to stop the picker from showing month days again. Just an idea, let me know how it goes!

**Comment by nickmayorga** [comment]
Thanks for the quick reply! Actually, I don't want onChange to trigger that way, I was asking for clarification if that is how it works currently, since I seem to have broken the month and year views by overriding onChange with my own callback.

The behavior I'm currently seeing is that I can zoom out to months or years, but when I click a month or year to zoom back in the calendar is disappearing instead of drilling back down into the month or year.

**Comment by radubrehar** [comment]
Would be useful if you can share a reduced example reproducing the behavior. Maybe you could use http://www.webpackbin.com/ to prove it

**Comment by radubrehar** [comment]
@nickmayorga we've had a major new release, v `5.3.8` is on npm with input integration, a nice `HistoryView` integrated into the navbar of the picker that allows you to sneak into years/months very nicely. Please have a look at that!
