### ISSUE TITLE
Webpack externals configuration is incorrect

### ISSUE THREAD

**Issue by moodysalem** [zippyui/react-date-picker#70]
I'm trying to include the nomoment distribution. If I look at the webpack generated factory, it is trying to require uppercase React. It should be trying to require lowercase react.

	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("React"), require("moment"));
	else if(typeof define === 'function' && define.amd)
		define(["React", "moment"], factory);
	else if(typeof exports === 'object')
		exports["DatePicker"] = factory(require("React"), require("moment"));
	else
		root["DatePicker"] = factory(root["React"], root["moment"]);

This is an example of a proper externals configuration

    externals: {
      'react': { commonjs: 'react', commonjs2: 'react', amd: 'react', root: 'React' }
    },

**Comment by radubrehar** [comment]
We're no longer distributing a single bundle file with our new v5 picker, so don't think this is applicable any more.

See http://zippyui.com/docs/react-date-picker/examples/1 for some nice examples
