### ISSUE TITLE
Selected value in a range

### ISSUE THREAD

**Issue by pstahmer** [zippyui/react-date-picker#71]
Hello,

I've found this library to be very useful and customizable, but I have one issue with it that I'm not getting the logic behind. It looks like things are set up so that if a `range` prop is provided the `dp-value` class stops getting applied. In each of your views there's a block 

```
if (!this.props.range){
  props.moment = moment(props.date).startOf('month')
}
```

which causes the issue. Is there a particular reason for this? All I can think of is that you might have just not wanted two highlights on a view (one for range, one for selection). For the `month` view I can get around it with `onRenderDay`, but for the other views there isn't an equivalent prop.

It seems to me like you could easily expose this functionality, but keep a clean UI by adding a style to `.dp-value.dp-in-range` which follows the `.dp-in-range` rules. If you'd like I can open PR to show how this would look.

**Comment by radubrehar** [comment]
We're not allowing both a `date` selected and a `range`, since it's not a feasible use-case.
Could you provide more insight into what you want to accomplish?

**Comment by pstahmer** [comment]
The particular use case I have is one where users have a range of valid dates, and can select a sub-range with two date pickers. The idea was to gray out any values outside the range, and have each picker highlight it's currently selected date when open.

**Comment by radubrehar** [comment]
You could use the `renderDay` prop function to hook your own selection logic when the user clicks a day. Besides that, you have dp-in-range for highlighting the current range. Do you think you could get the job done using these?

**Comment by pstahmer** [comment]
That's the initial workaround I described in my original post, but it only applies to the month view. It doesn't help with the year or decade views.

**Comment by radubrehar** [comment]
We've released a new version on npm, so you might want to check out the new release.
