### ISSUE TITLE
Is it possible to disable certain days?

### ISSUE THREAD

**Issue by jhnferraris** [zippyui/react-date-picker#72]
Is their a way that will allow me to select only days that are Saturdays or Sundays?

Thanks!

**Comment by radubrehar** [comment]
Sure - use the controlled `date` prop and check if the selected date is fine or not, and only update the prop if you are fine with the selection. Additionally, you can use the `renderDay` prop to customize how each day is displayed to give a visual feedback to the user.

**Comment by jhnferraris** [comment]
I see. I went with using the `date` prop and just handled the date if it is allowable using the change handler.  I might try `renderDay` when I have more time to look into it.

Thanks!
