### ISSUE TITLE
Date-picker updates to show the Day value - but not the Month and Year

### ISSUE THREAD

**Issue by hunthunthunt** [zippyui/react-date-picker#74]
See in the attached example which is using the `react-date-picker` component.

![dp-example](https://cloud.githubusercontent.com/assets/226283/14492533/d4b5dc6a-0177-11e6-952c-52b9cf35d1f7.gif)

As the day value in the input is changed, it's reflected in the date-picker. However, I would expect the picker to change it's view to reflect the changed month and year.

i.e. when month is updated, update the picker to reflect the selected month (don't stay on initially selected month)
i.e. when year is updated, change picker to reflect the selected year (don't stay on initially selected year)

Is there a way to prompt the picker to update it's view to show the currently selected date? Or is this a bug?

**Comment by radubrehar** [comment]
There are 2 props that are related: `date` - which decides what is highlighted, and `viewDate` which decides what date is currently in the view. You are probably only using `date` and expect to see the picker navigate - you have to use `viewDate` for that. So a combination of the two will solve your problem.

Hope you find this very configurable/flexible :)

**Comment by hunthunthunt** [comment]
Awesome, thanks - this is perfect.

Big thanks for prompt reply also ;)

**Comment by radubrehar** [comment]
We've had a big release last week, `5.3.8` is live on npm & on our docs site at http://zippyui.com/docs/react-date-picker. We have very good input integration & a lot of other good stuff.

So I'm closing this issue, and hope you'll find the component useful
