### ISSUE TITLE
missing local when setting weekDayNames

### ISSUE THREAD

**Issue by joodies** [zippyui/react-date-picker#80]
Hi,

`weekDayNames={Moment.weekdaysMin()}`

English weekday names displayed all the time in this way, in spite of changing local.

**Comment by radubrehar** [comment]
If you explicitly pass the `weekDayNames`, they are displayed just as you provide them.

**Comment by radubrehar** [comment]
We've released v `5.3.2` on npm today, which is a major rewrite of our old & stable v4. The new release includes an impressive list of new features:

 * overhauled keyboard navigation
 * date input integration
 * time support
 * multi month views
 * transitions on navigation
 * a lot more.

See zippyui.com/docs/react-date-picker/examples for some examples!
