### ISSUE TITLE
How to go from MonthView to DateField

### ISSUE THREAD

**Issue by jgutta** [zippyui/react-date-picker#82]
Hello!
 Your date picker looks great, I have a question about its use that isn't covered in your documentation. I have your date picker in use, and what is there works, the problem is that only the MonthlyView calendar displays. I want to DateField view, but there doesn't appear to be a prop to pass to change between the two. How do I enable the DateField view? Thanks in advance for your help.

**Comment by radubrehar** [comment]
What version of the date picker are you using?

**Comment by radubrehar** [comment]
Please use the latest `5.3.2` version released on npm today which is a major rewrite of our v4.

Usage example:

```jsx
import 'react-date-picker/index.css'
import { DateField } from 'react-date-picker'

<DateField date={yourDate} dateFormat="YYYY-MM-DD" onChange={(dateString) => {console.log(dateString)} }/>
```

**Comment by radubrehar** [comment]
Let us know how it goes!

**Comment by jgutta** [comment]
Awesome, thanks for your help!

**Comment by radubrehar** [comment]
Glad to help!
