### ISSUE TITLE
Range via drag

### ISSUE THREAD

**Issue by tquetano-r7** [zippyui/react-date-picker#83]
I've been playing with the latest release and LOVE the range feature! The only thing that could make the experience better is if the range could be denoted by click-drag-release. Something along the lines of this flow:

- onmousedown, capture start date and activate onmouseover listeners
- onmouseover each day, capture end date and reflect range visually
- onmouseup, deactivate onmouseover listeners

Could something like this happen? A humble feature request? :)

**Comment by radubrehar** [comment]
Have a look at `highlightRangeOnMouseMove` prop. It might be exactly what you need :)

**Comment by tquetano-r7** [comment]
Ah nice! Can do. 

Along these lines, though, I will offer a piece of constructive criticism... call out all the available props in your documentation. I spent a lot of time rifling through your source code to figure out props I could use, and even that was tough since proptypes aren't used every one available. Who knows, maybe I missed in the documentation, but a prop banned like that would have stood out to me and saved us some time.

Not trying to be negative, cuz this component is friggin brilliant. Just offering my two cents.

**Comment by radubrehar** [comment]
Thanks a bunch for the constructive advice! Definitely agree!
We're just building up http://zippyui.com/docs/react-date-picker the docs site - you have an examples tab as well - not very detailed though.
It took us more than expected to have this major rewrite of the component, so the docs still leave a LOT of room for improvement, but expect new things to be added in the following days/weeks.
