### ISSUE TITLE
Hackerone theme doesn't work

### ISSUE THREAD

**Issue by Develliot** [zippyui/react-date-picker#87]
The Hackerone theme works in 4.0.10 IIRC but not the latest version, I looks like the class names are all different

**Comment by radubrehar** [comment]
Yep, we've had a majore rewrite and dropped the hackerone theme - one of the reasons we had a major version bump. The default theme is pretty nice though, and if you want, you can build a new theme, either from scratch, or based on the default theme (`import "style/theme/default.scss")` by overriding some color variables.
