### ISSUE TITLE
style/base.scss not compile standart sass preprocessor

### ISSUE THREAD

**Issue by me6iaton** [zippyui/react-date-picker#92]
this line https://github.com/zippyui/react-date-picker/blob/master/style/base.scss#L121
specific to webpack/css-loader

**Comment by radubrehar** [comment]
Thanks for pointing that out! So the solution would be to specify the path to node_modules/react-flex...?

**Comment by me6iaton** [comment]
yes, it will work

**Comment by radubrehar** [comment]
Don't quite like it, but I think it's the best solution for now!

v `5.3.10` is out on npm. Thanks!
