### ISSUE TITLE
Potential bug with React mouseover events and weird behaviour on multiple screens.

### ISSUE THREAD

**Issue by malreynolds** [zippyui/react-date-picker#93]
Hi, I'm using version 5.3.9, Google Chrome, Ubuntu 16.04.

I have a ul in which the li's detect onMouseOver and onMouseOut events.  In one of those li's I have a DateField. For some reason, when I select a new date and click OK, the DateField closes, but the DateField still thinks I'm hovering over it, and hence its parent li also thinks it's being hovered over. 

The only way to reset this is to forcefully hover over the li and then hover out, which will properly trigger the onMouseLeave event.

Something else, which I think is a different manifestation of the same issue can be seen in the main document page http://zippyui.com/docs/react-date-picker

Steps to reproduce would be to:

1. Scroll down to "Using a DateField"
2. Click on the DateField, select any date and click OK (the DateField should close).
3. Move your mouse to another monitor, which doesn't have a browser in it. 
4. Move your mouse back into the original monitor where your browser is -- The DateField now opens, even if you didn't tell it to open. 

Another weird behaviour with multiple monitors is when you open the DateField and move your mouse to another monitor - the DateField disappears and reappears as you do that.

Thanks!

**Comment by radubrehar** [comment]
I managed to repro the scenario with the steps above. The fact is, you have to click outside the browser, then click the browser again. At that point, since the date field receives focus, it expands the picker. It is the intended behavior. You can control that with `expandOnFocus`, which is `true` by default. Or you can programatically focus something else to make the picker collapse.

Let us know how it goes.

**Comment by malreynolds** [comment]
Hi, again!

I had a play around with expandOnFocus.

>  The fact is, you have to click outside the browser, then click the browser again. 

That's not the case in my experience. I think the reason is because on my Linux machine, the focused window is the one which the mouse is currently hovering over, so I don't need to click to trigger the event. Either way, I'm still not convinced it's the right behaviour to close/reopen the field on blur/focus events.
I think there should be something like "dontCloseOnBlur" to control this. 

It also feels a bit awkward that if you have expandOnFocus enabled and you have had the DateField open at some point, when you trigger a window focus event, the DateField will reopen regardless of whether you had it opened before the blur event. Hope that's clear.

Last thing, I think none of this is related to my initial problem, which was that the onMouseOver event persists even if we've closed the DateField window. I created a hacky way of fixing this, but the solution is specific and only works in my case. I suspect that's a React bug more than it is related to the datepicker component, but can't really confirm.

**Comment by radubrehar** [comment]
> It also feels a bit awkward that if you have expandOnFocus enabled and you have had the DateField open at some point, when you trigger a window focus event, the DateField will reopen regardless of whether you had it opened before the blur event. Hope that's clear.

The DateField will only reopen if it had focus before you blurred the browser window. Correct?

Another thing you can use - you have the controlled `expanded` prop, so you can use that to control expand/collapse - also in conjunction with `onExpandChange(bool)`.

**Comment by malreynolds** [comment]
Hi, yes, I can confirm that it only reopens if it had focus before, which I found not intuitive as when you close the DateField window by either Close, OK or selecting a date, the whole element is still focused, but one would expect the field not to reopen, unless you explicitly tell it to.

I think I will be able to solve this problem using the expanded prop, so feel free to close this if you feel the above is not an issue.

Thanks!

**Comment by radubrehar** [comment]
Not an issue in my opinion.
You could simply blur the DateField (by focusing something else - eg `document.body`) when `onChange` happens to obtain the desired behavior.

Otherwise, hope you find it useful :)
