### ISSUE TITLE
(Question) Controlling the input field of DateField externally

### ISSUE THREAD

**Issue by malreynolds** [zippyui/react-date-picker#95]
Is there a standard recipe which allows us to control the DateFields input field by passing a prop?

I tried setting the value prop like that:

`"value={this.props.startDate.format(this.props.dateFormat)}"`

and this only works until I manually select a new date from the date picker, after which the value prop is ignored.

I also tried setting the date prop and not setting value like that :

`date={this.props.endDate}`

but the input field is always empty or shows "Invalid Date", depending on whether or not forceValidState is set. I am 100% sure this.props.endDate as I can console log it's value and it's being used by other components as well(it's managed by Redux state).  This leads me to believe that either I'm using the date property the wrong way, or something inside DateField is setting it to something else - (thus why I'm getting "Invalid Date")

Thanks!

**Comment by radubrehar** [comment]
The `DateField` expects a `value` or `defaultValue` property, not a `date` property.

Thanks for pointing that out! We've just fixed the controlled `value` prop so it now behaves properly. See v `5.3.11` on npm

PS: `forceValidDate` not `forceValidState`

**Comment by malreynolds** [comment]
I can confirm this now works as expected, thanks!

**Comment by radubrehar** [comment]
Great!
